services:
  glovo-postgres:
    image: postgres:15-alpine
    restart: always
    container_name: db-postgres
    environment:
      POSTGRES_USER: glovoTeam
      POSTGRES_PASSWORD: glovoTeam
      POSTGRES_DB: glovoDB
    ports:
      - "5442:5432"
    networks:
      - glovoApp-backend
    volumes:
      - glovo-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "glovoTeam", "-d", "glovoDB" ]
      interval: 30s
      timeout: 20s
      retries: 3
    mem_reservation: 128M

  minio:
    build:
      context: .
      dockerfile: DockerfileMinio
    container_name: glovoapp-minio-1
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data/runtime --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - glovoApp-backend
    volumes:
      - ./minio_data:/data/initial
      - ./scripts/export_minio.sh:/scripts/export_minio.sh:ro # Исправлено
      - minio_runtime_data:/data/runtime
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 5
    mem_reservation: 128M

  mc:
    build:
      context: .
      dockerfile: DockerfileMc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/categories;
      mc mb myminio/subcategories;
      mc mb myminio/establishments;
      mc mb myminio/products;
      mc cp --recursive /data/initial/categories/* myminio/categories;
      mc cp --recursive /data/initial/subcategories/* myminio/subcategories;
      mc cp --recursive /data/initial/establishments/* myminio/establishments;
      mc cp --recursive /data/initial/products/* myminio/products;
      mc policy set public myminio/categories;
      mc policy set public myminio/subcategories;
      mc policy set public myminio/establishments;
      mc policy set public myminio/products;
      echo 'Данные успешно загружены в MinIO.';
      "
    volumes:
      - ./minio_data:/data/initial:ro
    networks:
      - glovoApp-backend

  redis:
    image: bitnami/redis:latest
    container_name: cache-redis
    environment:
      REDIS_PASSWORD: glovoTeam
    ports:
      - "6379:6379"
    networks:
      - glovoApp-backend
    mem_reservation: 256M

volumes:
  glovo-data: {}
  minio_runtime_data: {}

networks:
  glovoApp-backend:
    driver: bridge
