version: '3.8'
services:
  glovo-postgres:
    image: postgres:15-alpine
    restart: always
    container_name: db-pg
    environment:
      POSTGRES_USER: glovoTeam
      POSTGRES_PASSWORD: glovoTeam
      POSTGRES_DB: glovoDB
    ports:
      - "5442:5432"
    volumes:
      - glovo-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "glovoTeam", "-d", "glovoDB" ]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API порт
      - "9001:9001"  # Консоль управления
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  glovo-data: {}
  minio_data: {}