version: '3.8'
services:
  glovo-postgres:
    image: postgres:15-alpine
    restart: always
    container_name: db-postgres
    environment:
      POSTGRES_USER: glovoTeam
      POSTGRES_PASSWORD: glovoTeam
      POSTGRES_DB: glovoDB
    ports:
      - "5442:5432"
    networks:
      - glovoApp-backend
    volumes:
      - glovo-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "glovoTeam", "-d", "glovoDB" ]
      interval: 30s
      timeout: 20s
      retries: 3
    mem_reservation: 128M

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - glovoApp-backend
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    mem_reservation: 128M
  redis:
    image: bitnami/redis:latest
    container_name: cache-redis
    environment:
      REDIS_PASSWORD: glovoTeam
    ports:
      - "6379:6379"
    networks:
      - glovoApp-backend
    mem_reservation: 256M
  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase-cli
    depends_on:
      glovo-postgres:
        condition: service_healthy
    networks:
      - glovoApp-backend
    volumes:
      - C:/Users/malibuchka/Desktop/glovoAppSecurity — копия/src/main/resources/db/changelog:/liquibase/changelog
    environment:
      LIQUIBASE_COMMAND_URL: "jdbc:postgresql://glovo-postgres:5432/glovoDB"
      LIQUIBASE_COMMAND_USERNAME: "glovoTeam"
      LIQUIBASE_COMMAND_PASSWORD: "glovoTeam"
      LIQUIBASE_COMMAND_CHANGELOG_FILE: "changelog/init/full-database-changelog.xml"
    entrypoint:
      - liquibase
      - generate-changelog
      - --includeObjects=".*"
      - --dataOutputDirectory="changelog/init"

volumes:
  glovo-data: {}
  minio_data: {}
networks:
  glovoApp-backend:
    driver: bridge