searchPath=classpath:db/changelog/
changeLogFile=src/main/resources/db/changelog/master.xml
url=jdbc:postgresql://localhost:5442/glovoDB
username=glovoTeam
password=glovoTeam
driver=org.postgresql.Driver
referenceUrl=hibernate:spring:com.api.glovoCRM.Models?dialect=org.hibernate.dialect.PostgreSQLDialect



