spring.application.name=glovoCRM
spring.datasource.url=jdbc:postgresql://localhost:5442/glovoDB
spring.datasource.username=glovoTeam
spring.datasource.password=glovoTeam
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=/db/changelog/master.xml
spring.liquibase.enabled=true


logging.level.root = info

minio.endpoint=http://localhost:9000
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.buckets.categories=categories
minio.buckets.establishments=establishments
minio.buckets.products=products
minio.buckets.subcategories=subcategories
minio.max-file-size-in-mb=10
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
minio.buffer = 8192


spring.task.execution.pool.core-size=4
spring.task.execution.pool.max-size=8
spring.task.execution.pool.queue-capacity=100

spring.devtools.livereload.enabled=false
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=20m
cash.duration = 20
cash.maxSize = 500

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.title=Glovo API

bot.token=7808413920:AAFzii7TkqcV1RreyUYh8zqKLUAQvDO_Gqs
openrouter.api.key=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

bot.send.code.token = ${BOT_SEND_TOKEN}

spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub



spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
spring.security.oauth2.client.registration.github.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.github.client-name=GitHub
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=login


spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/login/oauth2/code/facebook
spring.security.oauth2.client.registration.facebook.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.facebook.client-name=Facebook
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v18.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v18.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/v18.0/me?fields=id,name,email,picture
spring.security.oauth2.client.provider.facebook.user-name-attribute=name


jwt.access.secret=af474737f0b983d7372eb068fac962f4b044eb1c5016d3602e42a122b4c61ccbbb7e70d4f4b3a4145b993acdb8220bb07a1ab1e590872c68ddbd3bb422497251
jwt.refresh.secret=af474737f0b983d7372eb068fac962f4b044eb1c5016d3602e42a122b4c61ccbbb7e70d4f4b3a4145b993acdb8220bb07a1ab1e590872c68ddbd3bb422497252
#5 (10 * 60 * 1000) ???? ??????? access 10 ?????
jwt.access.expiration=300000
# 7 ???? (7 * 24 * 60 * 60 * 1000) ???? refresh 7 ?????
jwt.refresh.expiration=604800000
auth.code.expiration = 60
auth.link.expiration = 180
# Redis if localhost
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=glovoTeam


# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



twilio.account-sid = ${TWILIO_ACCOUNT_SID}
twilio.auth-token = ${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}

spring.config.import=optional:file:.env[.properties]
admin.email = malibukadyraliev332@gmail.com
admin.chat.id=1058635656